### PR TITLE
WIP: lodash: refine implicit and explicit chaining

### PR DESCRIPTION
**Pull request by rmg**
Add support for implicit and explicit chaining by defining a separate type for each that defines chained variants of the main API.

This is a continuation of what I started in #47 where I explored a different approach but ended up backing it out, leaving only a collection of unrelated lodash improvements.

/cc @STRML

### CODE REVIEW

**Comment by rmg** [comment]
@marudor you mentioned "refining the tests" in #49. If you want to give me some pointers as to what you're looking for I can make this PR a little closer to your ideal.

**Comment by marudor** [comment]
@rmg mainly matching the structure of flow-typed.
So negative tests with // $ExpectError.
I don't have support for that in flowInterfaces though.

**Comment by darky** [comment]
Any activity here? Would it be merged or some commits added?

**Comment by rmg** [comment]
@darky there is still more work to do, but I haven't been spending any time on it lately. Is it something you want to work on?

**Comment by marudor** [comment]
@rmg I've merged lodash with flow-typed now.
Could you create a new PR for this here: https://github.com/flowtype/flow-typed

**Pull request closed without merging**
